name: Update Podcast RSS

on:
  schedule:
    - cron: "15 4 * * *"  # Runs daily at 10:15 PM CST (4:15 AM UTC)
  workflow_dispatch:  # Allows manual trigger

jobs:
  update_rss:
    runs-on: ubuntu-22.04  # Explicitly use stable Ubuntu version

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Fetch New Episodes
        run: python fetch_new_episodes.py  # Fetches new episodes and updates CSV

      - name: Run RSS Generator Script
        run: python generate_rss.py  # Generates updated RSS feed

      - name: Commit and Push Updated Files
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          git add reiss_daf_mp3s.csv reiss_daf_podcast.xml
          git commit -m "Updated CSV and RSS Feed" || echo "No changes to commit"
          git push origin main
