name: Update Podcast RSS

on:
  schedule:
    - cron: "15 4 * * *"  # Runs daily at 10:15 PM CST (4:15 AM UTC)
  workflow_dispatch:   # Allows manual trigger

jobs:
  update_rss:
    runs-on: ubuntu-22.04  # Use stable Ubuntu version

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full repo history for commits

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Fetch New Episodes
        run: python fetch_new_episodes.py  # Fetches new episodes and updates CSV

      - name: Run RSS Generator Script
        run: python generate_rss.py  # Generates updated RSS feed

      - name: Commit and Push Updated Files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git pull origin main  # Ensure latest changes before pushing
          git add reiss_daf_mp3s.csv reiss_daf_podcast.xml
          git diff --quiet && git diff --staged --quiet || git commit -m "Updated CSV and RSS Feed"
          git push origin main || echo "No changes to push"
